# MODEL 
model: google/gemma-2-2b-it
model_name: gemma-2-2b-it

# PATHS
results_path: ${oc.env:PROJECT_ROOT}/results/${attribute}_${token_position}/
data_path: ${oc.env:PROJECT_ROOT}/data

stored_vectors_path: ${oc.env:PROJECT_ROOT}/stored_vectors

directions_path: ${oc.env:PROJECT_ROOT}/stored_vectors/innocuous_directions_gemma-2-2b-it_emoji_${token_position}.pt

prompts_path: ${data_path}/refusal/harmful_prompts.json  

# STEERING 
attribute: emoji
token_position: -2
steering_weights:  [1, 1.5, 1.75, 2, 2.25, 2.5] 
steering_layers: [12, 13, 14]            # 0-indexed

# COMPLETIONS
max_new_tokens: 128

# EVALUATION
val_samples: 100 
eval_source: test                 # choices: [val, test]

# Evaluation methods & ranking
eval_methods: [llamaguard2] 

device: cuda        
seed: 42
