# MODEL 
model: meta-llama/Llama-3.1-8B-Instruct
model_name: Llama-3.1-8B-Instruct

# PATHS
results_path: ${oc.env:PROJECT_ROOT}/stored_vectors/
# directions_path: ${oc.env:PROJECT_ROOT}/stored_vectors/direction_raw_${attribute}_${model_name}.pt
directions_path: ${oc.env:PROJECT_ROOT}/stored_vectors/innocuous_directions_${model_name}_${attribute}_-1.pt

methods: [svd, mean_null, qr, gram_schmidt, whitening]
num_samples: 700

# EVALUATION
device: cuda        
seed: 42

# HYDRA
attribute: year