model: google/gemma-2-2b-it
model_name: gemma-2-2b-it

num_train_samples: 128
num_val_samples: 32   
token_positions: [-1]

device: cuda

refusal_directions_path: ${oc.env:PROJECT_ROOT}/stored_vectors/refusal_directions_${model_name}.pt

instruct_following_data_path: ${oc.env:PROJECT_ROOT}/data/instruction_following/ifeval_augmented_filtered.jsonl

instruct_directions_path: ${oc.env:PROJECT_ROOT}/stored_vectors/innocuous_directions_${model_name}.pt

refusal_direction_layer: 11
refusal_direction_token_position: -1

instruct_direction_layer: 11
instruct_direction_token_position: -1

attributes: 
  # - uppercase
  # - lowercase
  # - no_comma
  # - json
  # - title_fmt
  - emoji